{"name": "test_unsuccessfull_delete_courier_with_incorrect_id", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Курьера с таким id нет.' == 'Курьера с таким id нет'\n  \n  \u001b[0m\u001b[91m- Курьера с таким id нет\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  \u001b[92m+ Курьера с таким id нет.\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  ?                       +\u001b[90m\u001b[39;49;00m", "trace": "self = <tests.test_delete_courier.TestDeleteCourier object at 0x000002AE1F5F03E0>\n\n    def test_unsuccessfull_delete_courier_with_incorrect_id(self):\n            with allure.step(\"отправляем запрос на удаление курьера и сохраняем ответ в переменную response\"):\n                response = requests.delete(Path.CREATE_COURIER + f\"/111\")\n            with allure.step(\"проверка кода и тела ответа\"):\n                assert response.status_code == 404\n>               assert response.json()[\"message\"] == Errors.DELETE_ERROR_WITH_INCORRECT_ID\nE               AssertionError: assert 'Курьера с таким id нет.' == 'Курьера с таким id нет'\nE                 \nE                 \u001b[0m\u001b[91m- Курьера с таким id нет\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\nE                 \u001b[92m+ Курьера с таким id нет.\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\nE                 ?                       +\u001b[90m\u001b[39;49;00m\n\ntests\\test_delete_courier.py:40: AssertionError"}, "steps": [{"name": "отправляем запрос на удаление курьера и сохраняем ответ в переменную response", "status": "passed", "start": 1757435788745, "stop": 1757435789066}, {"name": "проверка кода и тела ответа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Курьера с таким id нет.' == 'Курьера с таким id нет'\n  \n  \u001b[0m\u001b[91m- Курьера с таким id нет\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  \u001b[92m+ Курьера с таким id нет.\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  ?                       +\u001b[90m\u001b[39;49;00m\n", "trace": "  File \"c:\\Users\\Dmitry\\Desktop\\Python YP\\Sprint_7\\tests\\test_delete_courier.py\", line 40, in test_unsuccessfull_delete_courier_with_incorrect_id\n    assert response.json()[\"message\"] == Errors.DELETE_ERROR_WITH_INCORRECT_ID\n"}, "start": 1757435789066, "stop": 1757435789066}], "start": 1757435788745, "stop": 1757435789067, "uuid": "d089b142-7e85-4591-82f8-a3e83a952603", "historyId": "cabb313939fb77dafe2142c0a3e33023", "testCaseId": "cabb313939fb77dafe2142c0a3e33023", "fullName": "tests.test_delete_courier.TestDeleteCourier#test_unsuccessfull_delete_courier_with_incorrect_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-A445VSF"}, {"name": "thread", "value": "9672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_delete_courier"}], "titlePath": ["tests", "test_delete_courier.py", "TestDeleteCourier"]}